train:
  exp-name: "ViT"
  nclasses: 20
  data: "data"
  image-size: 384
  data-augmentation: 1
  model-name: "vit"
  version: 0
  batch-norm: 0
  epochs: 10
  batch-size: 16
  optim-name: "sgd"
  lr: 0.001
  lr-gamma: 0.5
  lr-step: 15
  seed: 0
  dropout: 0
  fc-dim: 50
  freeze-weights: 1
  momentum: 0.9